spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        register-enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reptile-service
          uri: lb://reptile-service
          orser: 1
          predicates:
            - Path=/reptile/**
          filters:
            - StripPrefix=1

server:
  port: 8082
mybatis:
  mapperLocations: classpath:mapper/*.xml

